# Generated by Django 4.1.6 on 2023-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0028_alter_order_deliveryagt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='recv_challan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
