# Generated by Django 4.1.6 on 2023-03-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0029_alter_replacement_recv_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Deposited to bank', 'Deposited to bank'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
