# Generated by Django 4.1.6 on 2023-03-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0032_alter_master_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentsts',
            field=models.CharField(choices=[('Cash Received', 'Cash Received'), ('Ondate Cheque Received', 'Ondate Cheque Received'), ('Postdate Cheque Received', 'Postdate Cheque Received'), ('Online NEFT', 'Online NEFT'), ('UPI Payment', 'UPI Payment'), ('No Payment', 'No Payment')], max_length=50),
        ),
    ]
