# Generated by Django 4.1.6 on 2023-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0033_alter_order_paymentsts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='delv_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
