# Generated by Django 4.1.6 on 2023-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0035_alter_master_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
