# Generated by Django 4.1.6 on 2023-04-28 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0037_alter_master_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('agent', models.CharField(choices=[('Goutam Halder', 'Goutam Halder'), ('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25)),
                ('shop', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('New Order', 'New Order'), ('Pending Order', 'Pending Order'), ('Partially Pending', 'Partially Pending'), ('Delivered', 'Delivered')], max_length=20)),
                ('order_details', models.TextField(max_length=400)),
                ('remarks', models.TextField(blank=True, max_length=400)),
            ],
        ),
    ]
