# Generated by Django 4.1.6 on 2023-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0038_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='remarks',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
