# Generated by Django 4.2 on 2023-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0040_alter_new_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Pending Material', 'Pending Material'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
