# Generated by Django 4.1.6 on 2023-05-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0041_alter_new_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
    ]
