# Generated by Django 4.1.6 on 2023-08-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0042_alter_master_agent_alter_new_order_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='bar',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
