# Generated by Django 4.1.6 on 2023-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0043_replacement_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='bar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
