# Generated by Django 4.1.6 on 2023-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0044_alter_replacement_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='item',
            field=models.TextField(max_length=400),
        ),
    ]
