# Generated by Django 4.1.6 on 2023-09-12 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0045_alter_replacement_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='boat_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('full_address', models.TextField(max_length=400)),
                ('landmark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=25)),
                ('issue', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=15)),
                ('inv_img', models.ImageField(blank=True, null=True, upload_to='boat_invoice/')),
                ('retailer', models.CharField(max_length=100)),
                ('retailer_ph', models.CharField(max_length=15)),
                ('pickup', models.CharField(choices=[('Home', 'Home'), ('Retailer', 'Retailer')], max_length=10)),
                ('agent', models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25)),
                ('status', models.CharField(blank=True, choices=[('New Ticket', 'New Ticket'), ('Ticket issued', 'Ticket issued'), ('Ticket resolved', 'Ticket resolved'), ('Ticket rejected', 'Ticket rejected')], max_length=25)),
                ('remarks', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
