# Generated by Django 4.1.6 on 2023-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0047_alter_boat_ticket_agent_alter_boat_ticket_inv_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat_ticket',
            name='inv_img',
            field=models.ImageField(upload_to='boat_invoice/'),
        ),
    ]
